---
version: '3'
services:

  web:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: gunicorn github_app.wsgi --reload --timeout 120 --log-file - --bind="0.0.0.0:8000"
