# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubCommit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_sha', models.CharField(max_length=64)),
                ('commit_url', models.URLField()),
                ('commit_date', models.DateTimeField()),
                ('commit_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GitHubUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('fullname', models.CharField(max_length=255)),
                ('avatar_url', models.URLField()),
                ('profile_url', models.URLField()),
                ('date_created', models.DateTimeField()),
                ('last_events_update', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='githubcommit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github_stats.GitHubUser'),
        ),
    ]
